"""folder_embedding column in folder table

Revision ID: 1e2cab304cac
Revises: c32fb8abe107
Create Date: 2025-12-29 15:15:04.787853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '1e2cab304cac'
down_revision: Union[str, None] = 'c32fb8abe107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    #sa.Column('embedding', Vector(dim=1536), nullable=True),
    op.add_column('folder', sa.Column('folder_embedding', Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'folder_embedding')
    # ### end Alembic commands ###
