"""adding bucketing mode boolean column to Folder table

Revision ID: 2994a72baf17
Revises: 9076b42a5b56
Create Date: 2025-12-23 12:56:56.367544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2994a72baf17'
down_revision: Union[str, None] = '9076b42a5b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('bucketing_mode', sa.Boolean(), nullable=True))

    op.execute("UPDATE folder SET bucketing_mode = false")

    op.alter_column("folder", "bucketing_mode", nullable=False)

    op.execute("UPDATE folder SET keywords = ARRAY[]::VARCHAR[]")

    op.execute("UPDATE folder SET url_patterns = ARRAY[]::VARCHAR[]")

    op.alter_column('folder', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('folder', 'url_patterns',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folder', 'url_patterns',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('folder', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('folder', 'bucketing_mode')
    # ### end Alembic commands ###
