"""adding in foreign contraint

Revision ID: 4a23460e20b9
Revises: 55170ec071fa
Create Date: 2026-01-23 12:11:14.992338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a23460e20b9'
down_revision: Union[str, None] = '55170ec071fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_tag', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('content_tag_content_id_fkey'), 'content_tag', type_='foreignkey')
    op.create_foreign_key(None, 'content_tag', 'content_item', ['content_id', 'user_id'], ['content_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_tag', type_='foreignkey')
    op.create_foreign_key(op.f('content_tag_content_id_fkey'), 'content_tag', 'content', ['content_id'], ['content_id'])
    op.drop_column('content_tag', 'user_id')
    # ### end Alembic commands ###
