"""getting rid of the UserTag table for simplicity

Revision ID: 59bbe3b9cb96
Revises: 8c28d27938c8
Create Date: 2026-01-21 11:43:35.990670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59bbe3b9cb96'
down_revision: Union[str, None] = '8c28d27938c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column as nullable first
    op.add_column('tag', sa.Column('user_id', sa.UUID(), nullable=True))

    # 2. DATA MIGRATION: Copy user_id from user_tag into tag
    # This matches the user_id to the tag_id so we don't lose ownership
    op.execute(
        """
        UPDATE tag 
        SET user_id = user_tag.user_id 
        FROM user_tag 
        WHERE tag.tag_id = user_tag.tag_id
        """
    )

    # 3. Clean up: Delete any tags that didn't have an owner (optional but safer)
    # If a tag doesn't have a user_id now, the NOT NULL constraint will still fail.
    op.execute("DELETE FROM tag WHERE user_id IS NULL")

    # 4. Now that every row has a user_id, we can safely set NOT NULL
    op.alter_column('tag', 'user_id', nullable=False)

    # 5. Apply the rest of your changes
    op.create_foreign_key(op.f('tag_user_id_fkey'), 'tag', 'users', ['user_id'], ['id'])
    
    op.alter_column('tag', 'first_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    
    op.drop_constraint('tag_tag_name_key', 'tag', type_='unique')

    # 6. Drop the old table LAST
    op.drop_table('user_tag')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_unique_constraint(op.f('tag_tag_name_key'), 'tag', ['tag_name'])
    op.alter_column('tag', 'first_created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('tag', 'user_id')
    op.create_table('user_tag',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], name=op.f('user_tag_tag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_tag_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name=op.f('user_tag_pkey'))
    )
    # ### end Alembic commands ###
