"""Added keyowrds and url_patterns in the Folder table

Revision ID: 9076b42a5b56
Revises: bb902acb986a
Create Date: 2025-12-22 12:43:59.420387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9076b42a5b56'
down_revision: Union[str, None] = 'bb902acb986a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('folder', sa.Column('url_patterns', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'url_patterns')
    op.drop_column('folder', 'keywords')
    # ### end Alembic commands ###
