"""adding decription column to Folder table

Revision ID: c32fb8abe107
Revises: 2994a72baf17
Create Date: 2025-12-29 14:34:22.233508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32fb8abe107'
down_revision: Union[str, None] = '2994a72baf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('folder', sa.Column('description', sa.String(), nullable=True))

    op.execute("UPDATE folder SET description = ''")

    op.alter_column('folder', 'description', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'description')
    # ### end Alembic commands ###
