"""adding in user embedding

Revision ID: dac411465e74
Revises: 4a23460e20b9
Create Date: 2026-01-24 21:11:01.473125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = 'dac411465e74'
down_revision: Union[str, None] = '4a23460e20b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_embedding', Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_embedding')
    # ### end Alembic commands ###
